---
- name: Database servers
  hosts: db_servers
  roles:
    - { role: mysql,  tags: [mysql] }
    - { role: backup, tags: [backup] }

- name: Web servers
  hosts: web_servers
  roles:
    - { role: haproxy, tags: [haproxy] }
    - { role: dino, tags: [dino] }

- name: Monitoring servers
  hosts: monitoring_servers
  roles:
    - { role: prometheus, tags: [prometheus] }
    - { role: grafana,    tags: [grafana] }
