- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted
- name: restart node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted
